#!/usr/bin/env bash
#
# realm
# realm
# 
# Author: Wess Cope (me@wess.io)
# Created: 12/21/2021
# 
# Copywrite (c) 2021 Wess.io
#

export REALM_HOME="${HOME}/.realm"
export REALM_CONFIG="${REALM_HOME}/config.sh"
export SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export SCRIPT_LIBS_DIR=${SCRIPT_ROOT}/libs
export SCRIPT_ENVS_DIR=${SCRIPT_ROOT}/envs
export SCRIPT_CMD_DIR=${SCRIPT_ROOT}/commands


## LIBRARIES
source ${SCRIPT_LIBS_DIR}/__echo.sh
source ${SCRIPT_LIBS_DIR}/__helpers.sh


## Check
source ${SCRIPT_CMD_DIR}/__check.sh

## Main
cmd=$1
shift

case $cmd in
  "setup")
    source ${SCRIPT_CMD_DIR}/__setup.sh
    ;;
  "check")
    source ${SCRIPT_CMD_DIR}/__check.sh
    ;;
  "init")
    source ${SCRIPT_CMD_DIR}/__init.sh
    ;;
  "edit")
    source ${SCRIPT_CMD_DIR}/__edit.sh
    ;; 
  "config")
    source ${SCRIPT_CMD_DIR}/__config.sh
    ;; 
  *)
    echo "Invalid command." | error
    ;;
esac


unset SCRIPT_ROOT
unset SCRIPT_LIBS_DIR
unset SCRIPT_CMD_DIR